version: '3'

services:
  # MariaDB für Moodle
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: moodleroot
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - db_data:/var/lib/mysql

  # Moodle
  moodle:
    image: bitnami/moodle:latest
    depends_on:
      - db
    environment:
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_DATABASE_NAME: moodle
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin
      MOODLE_SITE_NAME: MoKITUL
    ports:
      - "8080:8080"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata:/bitnami/moodledata

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

  # Ollama
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # MongoDB
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  db_data:
  moodle_data:
  moodledata:
  ollama_data:
  qdrant_data:
  mongodb_data:
