version: '3'

tasks:
  get-plugins:
    desc: Clone or update plugins based on existence and --newest flag
    cmds:
      - |
        echo "Cloning or updating plugins..."
        for repo in {{range .plugin_repos}}{{.}} {{end}}; do
          dir=$(basename "$repo" .git)
          if [ -d "$dir" ]; then
            if echo "{{.CLI_ARGS}}" | grep -q -- '--newest'; then
              echo "Updating $dir..."
              (cd "$dir" && git fetch && git pull) || { echo "Error: Failed to update $dir"; exit 1; }
            else
              echo "Directory $dir already exists. Use --newest flag to update."
            fi
          else
            echo "Cloning $dir..."
            git clone "{{.github_base_url}}/$repo" || { echo "Error: Failed to clone $dir"; exit 1; }
          fi
        done

  get-api:
    desc: Clone or update API based on existence and --newest flag
    cmds:
      - |
        echo "Cloning or updating API..."
        dir=$(basename "{{.api_repo}}" .git)
        if [ -d "$dir" ]; then
          if echo "{{.CLI_ARGS}}" | grep -q -- '--newest'; then
            echo "Updating $dir..."
            (cd "$dir" && git fetch && git pull) || { echo "Error: Failed to update $dir"; exit 1; }
          else
            echo "Directory $dir already exists. Use --newest flag to update."
          fi
        else
          echo "Cloning $dir..."
          git clone "{{.github_base_url}}/{{.api_repo}}.git" || { echo "Error: Failed to clone $dir"; exit 1; }
        fi

  get-moodle-client:
    desc: Clone or update Moodle client based on existence and --newest flag
    cmds:
      - |
        echo "Cloning or updating Moodle client..."
        dir=$(basename "{{.client_repo}}" .git)
        if [ -d "$dir" ]; then
          if echo "{{.CLI_ARGS}}" | grep -q -- '--newest'; then
            echo "Updating $dir..."
            (cd "$dir" && git fetch && git pull) || { echo "Error: Failed to update $dir"; exit 1; }
          else
            echo "Directory $dir already exists. Use --newest flag to update."
          fi
        else
          echo "Cloning $dir..."
          git clone "{{.github_base_url}}/{{.client_repo}}.git" || { echo "Error: Failed to clone $dir"; exit 1; }
        fi

  get-all:
    desc: Clone or update all repositories
    cmds:
      - task: get-plugins
      - task: get-api
      - task: get-moodle-client

  clean:
    desc: Remove all cloned repositories
    cmds:
      - |
        echo "Removing cloned plugin repositories..."
        for repo in {{.plugin_repos}}; do
          dir=$(basename "$repo" .git)
          if [ -d "$dir" ]; then
            echo "Removing $dir..."
            rm -rf "$dir"
          else
            echo "Directory $dir does not exist."
          fi
        done
        echo "Removing cloned API repository..."
        dir=$(basename "{{.api_repo}}" .git)
        if [ -d "$dir" ]; then
          echo "Removing $dir..."
          rm -rf "$dir"
        else
          echo "Directory $dir does not exist."
        fi
        echo "Removing cloned Moodle client repository..."
        dir=$(basename "{{.client_repo}}" .git)
        if [ -d "$dir" ]; then
          echo "Removing $dir..."
          rm -rf "$dir"
        else
          echo "Directory $dir does not exist."
        fi
        echo "All cloned repositories have been removed."
